### ISSUE TITLE
add a 'yum list' to show exact N-E:v-r for contents

### ISSUE THREAD

**Issue by kbsingh** [CentOS/sig-core-t_functional#3]
Can we add a yum list to the start of the test runs, this would need to be done after the yum repos are setup for the test.

This would give us a record in the test logs of the rpms that were used in the test run.

**Comment by tigalch** [comment]
added to 0_common/20_upgrade_all.sh

Am 12.06.2015 um 18:52 schrieb Karanbir Singh:

> Can we add a yum list to the start of the test runs, this would need to
> be done after the yum repos are setup for the test.
> 
> This would give us a record in the test logs of the rpms that were used
> in the test run.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CentOS/sig-core-t_functional/issues/3.

## 

Christoph Galuschka
CentOS-QA-Team member | IRC: tigalch

**Comment by kbsingh** [comment]
thanks!
