### ISSUE TITLE
Add test for secureboot signing.

### ISSUE THREAD

**Issue by toracat** [CentOS/sig-core-t_functional#8]
The kernel, grub2, and shim packages need to be checked for the secureboot signing key.

**Comment by arrfab** [comment]
Fixed with commits 9bd63278fc2d6aa7163e1e023f1a007197126b34 a592652c788f3ad90e852094a6ad7c84fd5e2ca6 and 25c93aa22cf9ce4309e63aa2a8d9a77a1da73552
Kernel is already checked through kernel_centos_keyring.sh test

**Comment by toracat** [comment]
kernel_centos_keyring.sh displays 'CentOS Linux kernel signing key' (provided by x509.genkey). Checking for the secureboot signing key may be done by running pesign on the /boot/vmlinuz file like so:

## $ pesign --show-signature --in /boot/vmlinuz-3.10.0-229.14.1.el7.x86_64

certificate address is 0x7fb1572a0df8
Content was not encrypted.
Content is detached; signature cannot be verified.
The signer's common name is Red Hat Inc.
No signer email address.
Signing time: Tue Sep 15, 2015
There were certs or crls included.

**Comment by arrfab** [comment]
Thanks, specific pesign tested added in commit 859aef73484ea262cfd05f043d9f7108fc12a2cb
